### ISSUE TITLE
"join google group" not working?

### ISSUE THREAD

**Issue by nsunami** [FreeOurKnowledge/website#27]
The "Join our Google Group" link on the [READNE.md file](https://github.com/FreeOurKnowledge/website/blob/b3a3c9693bc390686d11aca36e04e0537ceea4d7/README.md
) leads me to a page that says "content unavailable"

![image](https://user-images.githubusercontent.com/17035406/121030058-21616a00-c777-11eb-8c89-1867f3a1d231.png)

The link is currently redirected to this URL: 
https://groups.google.com/g/free-our-knowledge-community/

Is there a new join link that would work?

**Comment by CooperSmout** [comment]
I accidentally changed the google group name, should be fixed now
