### ISSUE TITLE
Help! Need to publish a campaign on FOK

### ISSUE THREAD

**Issue by hoorie** [FreeOurKnowledge/website#49]
Hi, 

We have finished preparing the "Postprint Pledge for Linguistics", and I am now trying to figure out how to publish this issue on the FOK website. 

Here is the issue: 
https://github.com/FreeOurKnowledge/website/issues/48

I am trying to make it appear on the FOK website as a campaign: 
https://freeourknowledge.org/

 Help would be appreciated. Thanks!

Ali

**Comment by CooperSmout** [comment]
have fixed this now by returning the base branch for Github Pages to the Master branch
